/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.igfl_allotment;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import static java.lang.System.out;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhi
 */
public class SORT extends javax.swing.JFrame {
 
    /**
     * Creates new form SORT
     */
    public SORT() {
        initComponents();
        show_user();
    }

     public ArrayList<User2> userList() {
        ArrayList<User2> userList=new ArrayList<>();
        try{  
Class.forName("com.mysql.jdbc.Driver");  

Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/houseallotment","root","root");
//here sonoo is database name, root is username and passwor) {
                String query="select * from applied_user ORDER BY job_band ASC,designation ASC,doj ASC,dop ASC";
                Statement stmt=con.createStatement();
                ResultSet rs=stmt.executeQuery(query);
                
                User2 user;
                while(rs.next())
                {
                    user=new User2(rs.getInt("p_no"),rs.getString("u_name"),rs.getString("job_band"),rs.getString("designation"),rs.getString("doj"),rs.getString("dop"),rs.getString("house_no"));
                   userList.add(user);
                }
                
                System.out.print(userList);
                
                
            }   
                catch( ClassNotFoundException | SQLException e){ System.out.println(e);}
         
        return userList;
       
                
                
        }
    

   public void show_user(){
       ArrayList<User2> list = userList();
       
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
   Object[] row=new Object[7];
  for(int i=0;i<list.size();i++){
      row[0]=list.get(i).getpno();
      row[1]=list.get(i).getuname();
      row[2]=list.get(i).getjob_band();
      row[3]=list.get(i).getdesig();
      row[4]=list.get(i).getdoj();
      row[5]=list.get(i).getjop();
      row[6]=list.get(i).gethouse_no();
      model.addRow(row);
      
      
   }
  
  
  Object model2= jTable1.getModel().getValueAt(1,0);
  System.out.println(model2);

  
  
  
  
  

   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(200, 60));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "P. NO", "NAME", "JOB BAND", "DESIGNATION", "DATE OF JOINING", "DATE OF PROM", "HOUSE NO"
            }
        ));
        jTable1.setMaximumSize(new java.awt.Dimension(600, 600));
        jTable1.setMinimumSize(new java.awt.Dimension(600, 600));
        jTable1.setPreferredSize(new java.awt.Dimension(500, 500));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 970, 280);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 410, 220, 40);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(368, 272, 0, 0);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 410, 230, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void close(){
WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
close();

try{  
Class.forName("com.mysql.jdbc.Driver");  
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/houseallotment","root","root");  
String sql2="truncate avail_final";
Statement stmt1=con.createStatement();
stmt1.executeUpdate(sql2);
}
catch(Exception e){System.out.println(e);
    }



try{  
Class.forName("com.mysql.jdbc.Driver");  
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/houseallotment","root","root");  
String sql2="insert into avail_final select * from avail_houses order by minjob_band asc";
Statement stmt1=con.createStatement();
stmt1.executeUpdate(sql2);
}
catch(Exception e){System.out.println(e);
    }
        
        
        try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/houseallotment","root","root");

            String query3="Truncate table sorted";
            Statement stmt=conn.createStatement();
            stmt.executeUpdate(query3);
        }
         catch(Exception e)
        {
            System.out.println();
        }
   
        
         try{
            
            
            Class.forName("com.mysql.jdbc.Driver");
Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/houseallotment","root","root");

            String query4="Truncate table combined";
            Statement stmt=conn.createStatement();
            stmt.executeUpdate(query4);
        }
         catch(Exception e)
        {
            System.out.println();
        }
   
        
        
        
        
       try{

int rows=jTable1.getRowCount();
Class.forName("com.mysql.jdbc.Driver").newInstance();
Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/houseallotment","root","root");
conn.setAutoCommit(false);





String queryco = "Insert into sorted(pers_no,u_name,job_band,designation,doj,dop,house_no) values (?,?,?,?,?,?,?)";

PreparedStatement pst = conn.prepareStatement(queryco);

for(int row = 0; row<rows; row++)
{
    String p_no=jTable1.getValueAt(row,0).toString();
    
    String u_name = (String)jTable1.getValueAt(row, 1);
    String job_band=jTable1.getValueAt(row,2).toString();
    String designation=(String)jTable1.getValueAt(row,3);
    if(designation.equals("Senior Manager"))
    designation="1";
         else if(designation.equals("Junior Manager"))
    designation="2";
         else if(designation.equals("Junior Assistant"))
    designation="3";
         else 
    designation="4";
         
         
    
    
    
    
    
    String doj=(String)jTable1.getValueAt(row,4);
    String dop=(String)jTable1.getValueAt(row,5);
    String house_no = (String)jTable1.getValueAt(row, 6);
   
    pst.setString(1, p_no);
    pst.setString(2, u_name);
    pst.setString(3, job_band);
    pst.setString(4,designation);
    pst.setString(5, doj);
    pst.setString(6, dop);
    pst.setString(7, house_no);
   
     

    pst.addBatch();
    
}
pst.executeBatch();

conn.commit();






}
catch(Exception e){
    System.out.println(e);
}
      
       
  try{


Class.forName("com.mysql.jdbc.Driver");
Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/houseallotment","root","root");     
       
 String query="insert into combined SELECT p_no,u_name,job_band,designation,doj,dop,house_no,p1,p2,alloted FROM sorted JOIN house_priority ON sorted.pers_no = house_priority.p_no ORDER BY job_band ASC,designation ASC,doj ASC,dop ASC";   
 
 Statement stmt=conn.createStatement();
 stmt.executeUpdate(query);
       
  }
  catch(Exception e){
    System.out.println(e);
}
       
  
  



//yahan se processing
try{     
    Class.forName("com.mysql.jdbc.Driver");  
     Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/houseallotment","root","root");
        
        Statement st=con.createStatement();
        int p_no=0;
        String p1="";
        String p2="";
        int job_band=0;
        
                String query="select  p_no,P1,P2,job_band from combined";
                ResultSet rs=st.executeQuery(query);
                               
                while(rs.next())
                {  
                   String h_no="x";
                String h_no2="x";
                    p_no=rs.getInt(1);
                    p1=rs.getString(2);
                    
                    p2=rs.getString(3);
                    
                   job_band=rs.getInt(4);
                
                
                    
              
              
            Statement st1=con.createStatement();  
           
           String query2=  "Select HOUSE_NUM from avail_final where HOUSE_NUM='"+p1+"'";
           
                   ResultSet rs2=st1.executeQuery(query2);
                   
                   if (rs2.next())
                   { 
                  
                 h_no=rs2.getString(1);   
                String qur ="select HOUSE_NUM from avail_final where '"+job_band+"'>=minjob_band and '"+job_band+"'<=maxjob_band and '"+h_no+"'=HOUSE_NUM";
                ResultSet rs3 =st1.executeQuery(qur);
            
                   
                   if(rs3.next())
                   {
                       h_no2=rs3.getString(1);
                   }
                   }
                   System.out.println(h_no2);
         
                 
                  
                    if(!h_no2.equals("x"))
                   
                  {
                       
                       
                       String query1="update combined set alloted='"+h_no2+"' where p_no='"+p_no+"' ";
                       st1.executeUpdate(query1);
                       //System.out.println(p_no+":"+h_no);
                      query= "delete from avail_final where HOUSE_NUM='"+h_no2+"' ";
                       st1.executeUpdate(query);
                
                      
                        
                   }
                
               if(h_no2.equals("x")){     
                    
                   Statement st2=con.createStatement();  
           
           String query3=  "Select HOUSE_NUM from avail_final where HOUSE_NUM='"+p2+"'";
           
                   ResultSet rs3=st2.executeQuery(query3);
                   
                   if (rs3.next())
                   { 
                  
                 h_no=rs3.getString(1);   
                String qur ="select HOUSE_NUM from avail_final where '"+job_band+"'>=minjob_band and '"+job_band+"'<=maxjob_band and '"+h_no+"'=HOUSE_NUM";
                ResultSet rs4 =st2.executeQuery(qur);
            
                   
                   if(rs4.next())
                   {
                       h_no2=rs4.getString(1);
                   }
                   }
                   System.out.println(h_no2);
         
                 
                  
                    if(!h_no2.equals("x"))
                   
                  {
                       
                       
                       String query1="update combined set alloted='"+h_no2+"' where p_no='"+p_no+"' ";
                       st1.executeUpdate(query1);
                       //System.out.println(p_no+":"+h_no);
                      query= "delete from avail_final where HOUSE_NUM='"+h_no2+"' ";
                       st1.executeUpdate(query);
                
                      
                        
                   }
               }
               
                
                   }          
    // TODO add your handling code here:
    }                                        
catch(Exception e) {System.out.println(e);}  
    /**
     * @param args the command line arguments
     */
 
     
    COMBINED r=new COMBINED();
    r.setVisible(true);




     
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
close();
        ADMINDESK r= new ADMINDESK();
r.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SORT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
